Karim, 3, A
Shamzik/HashMap pull request #1
Opened 2019-03-05 19:56 UTC by Shamzik

2019-03-18 09:45 UTC, sartuhin requested changes

2019-03-18 09:45 UTC, sartuhin commented on hash_map.h
> +    std::list<std::pair<const KeyType, ValueType>*> data1;
что такое data1 - название должно быть читаемым

2019-03-18 09:45 UTC, sartuhin commented on hash_map.h
> +    std::size_t __size;
почему в каком то случае используется _, где то __, где то вообще нет

2019-03-18 09:45 UTC, sartuhin commented on hash_map.h
> +    static const size_t k = 19, d = 17;
непонятные названия, константы должны отличаться по стилю

2019-03-18 09:45 UTC, sartuhin commented on hash_map.h
> +    std::list<std::pair<const KeyType, ValueType>*> data1;
pair<const KeyType, ValueType> использкентся много где - нужно вынести в typedef
другие повторения тоже

2019-03-18 09:45 UTC, sartuhin commented on hash_map.h
> +        size_t i = 0;
что такое i?

2019-03-19 17:53 UTC, Shamzik commented on hash_map.h
> +    std::size_t __size;
А как следует именовать переменную, если, например, в моём случае имя size занято функцией?

2019-03-19 17:54 UTC, Shamzik commented on hash_map.h
> +    static const size_t k = 19, d = 17;
Что значит, что имя отличается по стилю?

2019-03-19 18:29 UTC, Shamzik commented on hash_map.h
> +        size_t i = 0;
i играет роль индекса. Для каждого значения хэша существует абстрактный список, размер которого хранится в sizes. Я использую эту переменную для того, чтобы понять, на каком по счёту итераторе я остановился в этом абстрактном списке.

2019-03-23 09:36 UTC, sartuhin commented on hash_map.h
> +    std::size_t __size;
Можно добавить к ней осмысленное название или сделать так чтобы переменные и функции именовались в одном стиле.

2019-03-23 09:36 UTC, sartuhin commented on hash_map.h
> +    static const size_t k = 19, d = 17;
Обычно константы пишутся капсом с подчеркиванием, например MAX_SIZE

2019-03-23 09:37 UTC, sartuhin commented on hash_map.h
> +        size_t i = 0;
я понимаю, но из названия это абсолютно не следует.

2019-03-23 09:45 UTC, sartuhin requested changes

2019-03-23 09:45 UTC, sartuhin commented on hash_map.h
> +    Hash _hash_function;
здесь тоже не нужен _

2019-03-23 13:32 UTC, Shamzik commented on hash_map.h
> +    Hash _hash_function;
Нужен. Теперь это стиль полей моего класса.

2019-03-25 13:54 UTC, sartuhin requested changes

2019-03-25 13:54 UTC, sartuhin commented on hash_map.h
> +    typedef std::pair<const KeyType, ValueType> value_type;
Почему value_type но listIterator?
Нужна консистентность стилей.

2019-03-26 09:00 UTC, sartuhin approved these changes

2019-03-26 09:01 UTC, merged